AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  cloudtrail-events

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  KMSEventHandlerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: event_handlers
      Handler: kms_event_handler/app.lambda_handler
      Runtime: python3.7
      Events:
        KmsEvents:
          Type: CloudWatchEvent # More info about CloudWatchEvent Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#cloudwatchevent
          Properties:
            #EventBusName: your-event-bus-name #Uncomment this if your events are not on the 'default' event bus
            Pattern:
              source:
                - aws.kms
  CloudTrailS3Bucket:
    Type: AWS::S3::Bucket
    Properties: 
      AccessControl: Private
      BucketName: com.everythingbiig.aws.cloudtrail
      Tags: 
        - Key: domain
          Value: infrastructure
  CloudTrailS3BucketPolicy: 
    Type: AWS::S3::BucketPolicy
    Properties: 
      Bucket: !Ref CloudTrailS3Bucket
      PolicyDocument: 
        Version: '2012-10-17'
        Statement: 
        - Sid: AWSCloudTrailAclCheck20150319
          Effect: Allow
          Principal:
            Service:
            - cloudtrail.amazonaws.com
          Action: s3:GetBucketAcl
          Resource: arn:aws:s3:::com.everythingbiig.aws.cloudtrail
        - Sid: AWSCloudTrailWrite20150319
          Effect: Allow
          Principal:
            Service:
            - cloudtrail.amazonaws.com
          Action: s3:PutObject
          Resource: !Join [ "-", "arn:aws:s3:::com.everythingbiig.aws.cloudtrail/AWSLogs", [!Ref AWS::AccountId], "/*"]
          Condition:
            StringEquals: 
              s3:x-amz-acl: 'bucket-owner-full-control'

  AWSCloudTrail:
    Type: AWS::CloudTrail::Trail
    Properties: 
      # CloudWatchLogsLogGroupArn: String
      # CloudWatchLogsRoleArn: String
      # EnableLogFileValidation: Boolean
      # EventSelectors: 
      #   - ReadWriteType: All
      #     IncludeManagementEvents: true
      IncludeGlobalServiceEvents: true
      IsLogging: true
      IsMultiRegionTrail: false
      # KMSKeyId: String
      S3BucketName: com.everythingbiig.aws.cloudtrail
      S3KeyPrefix: /
      # SnsTopicName: String
      Tags: 
        - Key: domain
          Value: infrastructure
      TrailName: com.everythingbiig.aws.cloutrail
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  KMSEventHandlerFunctionArn:
    Description: "KMS Handler Function ARN"
    Value: !GetAtt KMSEventHandlerFunction.Arn
  KMSEventHandlerFunctionIamRole:
    Description: "Implicit IAM Role created for KMSEventHandlerFunction"
    Value: !GetAtt KMSEventHandlerFunctionRole.Arn
  # CloudTrailS3BucketArn:
  #   Description: Cloudtrail bucket ARN.
  #   Value:
  #     Fn::GetAtt:
  #     - CloudTrailS3Bucket
  #     - Arn