AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  cloudtrail-events

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  KMSEventHandlerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: event_handlers
      Handler: kms_event_handler/app.lambda_handler
      Runtime: python3.7
      Events:
        KmsEvents:
          Type: CloudWatchEvent # More info about CloudWatchEvent Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#cloudwatchevent
          Properties:
            #EventBusName: your-event-bus-name #Uncomment this if your events are not on the 'default' event bus
            Pattern:
              eventSource:
                - kms.amazonaws.com

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  KMSEventHandlerFunctionArn:
    Description: "KMS Handler Function ARN"
    Value: !GetAtt KMSEventHandlerFunction.Arn
  KMSEventHandlerFunctionIamRole:
    Description: "Implicit IAM Role created for KMSEventHandlerFunction"
    Value: !GetAtt KMSEventHandlerFunctionRole.Arn
